from django.db import models
from django.utils import timezone

# Create your models here.

class Users(models.Model):
    user_name = models.CharField(max_length = 100)
    birth_date = models.DateField()
    gender = models.CharField(max_length = 10)
    mobile_self = models.CharField(max_length = 13)
    mobile_family = models.CharField(max_length = 13)
    email = models.EmailField()
    home_no_name = models.CharField(max_length = 100)
    street_no_name = models.CharField(max_length = 100)
    area_name = models.CharField(max_length = 100)
    village_city = models.CharField(max_length = 100) 
    tehsil = models.CharField(max_length = 100)
    district = models.CharField(max_length = 100)
    state = models.CharField(max_length = 100) 
    country = models.CharField(max_length = 100)
    join_date = models.DateTimeField(auto_now_add = True)
    password = models.CharField(max_length = 50, min_length = 8)
    otp = models.CharField(max_length = 6)
    email_verify = models.CharField(max_length = 10, default = "unverified")

class Consultant(models.Model):
    consultant_name = models.CharField(max_length = 100)
    gender = models.CharField(max_length = 10)
    speciality_field = models.CharField(max_length = 100)
    consultant_regi_id = models.CharField(max_length = 100)
    mobile_no = models.CharField(max_length = 13)
    email = models.EmailField()
    hospital_name = models.CharField(max_length = 100)
    hospital_regi_id = models.CharField(max_length = 100)
    hospital_contact_no = models.CharField(max_length = 13)
    street_no_name = models.CharField(max_length = 100)
    area_name = models.CharField(max_length = 100)
    village_city = models.CharField(max_length = 100) 
    tehsil = models.CharField(max_length = 100)
    district = models.CharField(max_length = 100)
    state = models.CharField(max_length = 100) 
    country = models.CharField(max_length = 100)
    join_date = models.DateTimeField(auto_now_add = True)
    password = models.CharField(max_length = 50, min_length = 8)
    otp = models.CharField(max_length = 6)
    email_verify = models.CharField(max_length = 10, default = "unverified")

class Medical_shops(models.Model):
    shop_owner_name = models.CharField(max_length = 100)
    pharmasist_regi_id=models.CharField(max_length = 100)
    mobile_no = models.CharField(max_length = 13)
    email = models.EmailField()
    shop_name = models.CharField(max_length = 100)
    shop_regi_id = models.CharField(max_length = 100)
    shop_contact_no = models.CharField(max_length = 13)
    street_no_name = models.CharField(max_length = 100)
    area_name = models.CharField(max_length = 100)
    village_city = models.CharField(max_length = 100) 
    tehsil = models.CharField(max_length = 100)
    district = models.CharField(max_length = 100)
    state = models.CharField(max_length = 100) 
    country = models.CharField(max_length = 100)
    join_date = models.DateTimeField(auto_now_add = True)
    password = models.CharField(max_length = 50, min_length = 8)
    otp = models.CharField(max_length = 6)
    email_verify = models.CharField(max_length = 10, default = "unverified")
