# Generated by Django 5.0.4 on 2024-04-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_regi_id', models.CharField(max_length=100)),
                ('consultant_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('speciality_field', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_regi_id', models.CharField(max_length=100)),
                ('hospital_contact_no', models.CharField(max_length=13)),
                ('street_no_name', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('village_city', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=6)),
                ('email_verify', models.CharField(default='unverified', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_shops',
            fields=[
                ('shop_regi_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shop_owner_name', models.CharField(max_length=100)),
                ('pharmasist_regi_id', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_contact_no', models.CharField(max_length=13)),
                ('street_no_name', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('village_city', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=6)),
                ('email_verify', models.CharField(default='unverified', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile_self', models.CharField(max_length=13)),
                ('mobile_family', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('home_no_name', models.CharField(max_length=100)),
                ('street_no_name', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('village_city', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=6)),
                ('email_verify', models.CharField(default='unverified', max_length=10)),
            ],
        ),
    ]
