# Generated by Django 5.0.4 on 2024-04-06 14:43
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('consultant_regi_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('consultant_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('speciality_field', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_regi_id', models.CharField(max_length=100)),
                ('hospital_contact_no', models.CharField(max_length=13)),
                ('street_no_name', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('village_city', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=6)),
                ('email_verify', models.CharField(default='unverified', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_shops',
            fields=[
                ('shop_regi_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shop_owner_name', models.CharField(max_length=100)),
                ('pharmasist_regi_id', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_contact_no', models.CharField(max_length=13)),
                ('street_no_name', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('village_city', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=6)),
                ('email_verify', models.CharField(default='unverified', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='medicine_orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_item', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order_status', models.CharField(default='pending', max_length=20)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop_id', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_contact', models.CharField(max_length=13)),
                ('shop_owner', models.CharField(max_length=100)),
                ('owner_mobile', models.CharField(max_length=13)),
                ('shop_address', models.CharField(max_length=300)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_mobile_self', models.CharField(max_length=13)),
                ('user_mobile_family', models.CharField(max_length=13)),
                ('user_address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile_self', models.CharField(max_length=13)),
                ('mobile_family', models.CharField(max_length=13)),
                ('home_no_name', models.CharField(max_length=100)),
                ('street_no_name', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('village_city', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=6)),
                ('email_verify', models.CharField(default='unverified', max_length=10)),
            ],
        ),
    ]
